apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-infra
namePrefix: prod-

resources:
  - ../../base

patches:
  # Scale down flagd deployment to 0 replicas
  - target:
      kind: Deployment
      name: flagd
    patch: |
      - op: replace
        path: /spec/replicas
        value: 0
